[package]
name = "os"
version = "0.1.0"
authors = ["tytbu"]
edition = "2021"

[[bin]]
name = "kernel"
path = "src/init/init.rs"
test = false
doctest = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
